name: Build and Release (.NET Framework 4.8.3)

on:
  push:
    tags:
      - 'v*.*.*'   # 예: v1.0.0 같은 태그를 푸시할 때 실행됨

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 소스코드 가져오기
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. MSBuild 사용 준비 (Visual Studio 빌드 환경)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    # 3. NuGet 패키지 복원 (필요할 경우)
    - name: Restore NuGet packages
      run: nuget restore MyProject.sln

    # 4. 솔루션 빌드 (Release 모드, Any CPU)
    - name: Build solution
      run: msbuild MyProject.sln /p:Configuration=Release /p:Platform="Any CPU"

    # 5. 빌드 산출물 압축
    - name: Compress release output
      run: Compress-Archive -Path "MyProject\\bin\\Release\\*" -DestinationPath "release.zip"

    # 6. GitHub Release 생성 + zip 업로드
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 7. 아티팩트 업로드 (Actions 탭에서 다운로드 가능)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: MyProject/bin/Release/
